name: Update Blocklist

on:
  repository_dispatch:
    types: [block_domain]

jobs:
  update-list:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add Domain to Blocklist
        env:
          DOMAIN: ${{ github.event.client_payload.domain }}
        run: |
          echo "Received request to block: $DOMAIN"
          if [[ -z "$DOMAIN" || ! "$DOMAIN" =~ ^[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; then
            echo "Error: Invalid domain format"
            exit 1
          fi
          echo "$DOMAIN" >> blocklist.txt
          sort -u blocklist.txt -o blocklist.txt
          sed -i '/^$/d' blocklist.txt

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git add blocklist.txt
            git commit -m "Add $DOMAIN to blocklist"
            git push
          fi
